# app/config/security.yml
security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /user/home            
            logout:
                path:   /logout
                target: /home
            anonymous:    true

    access_control:
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/home, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /print, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/assessmentset/, role: ROLE_ADMIN }
        - { path: ^/objective/, role: ROLE_ADMIN }
        - { path: ^/scale/, role: ROLE_ADMIN }
        - { path: ^/scaleitem/, role: ROLE_ADMIN }
        - { path: ^/page/, role: ROLE_ADMIN }        
        - { path: ^/user_profile/, role: ROLE_USER }
        - { path: ^/journal/, role: ROLE_USER }
        - { path: ^/forum/, role: ROLE_USER }
        - { path: ^/comment/, role: ROLE_USER }
        - { path: ^/file/, role: ROLE_USER }
        - { path: ^/user/, role: ROLE_USER }
        - { path: ^/doc/, role: ROLE_USER }  
        - { path: ^/portfolio/, role: ROLE_USER }  
        - { path: ^/calendar/, role: ROLE_USER }         
        - { path: ^/course/, role: ROLE_USER }
        - { path: ^/term/, role: ROLE_USER }
        - { path: ^/roll/, role: ROLE_USER }
        - { path: ^/project/, role: ROLE_USER }
        - { path: ^/note/, role: ROLE_USER }
        - { path: ^/markup/, role: ROLE_INSTR }
        - { path: ^/markupset/, role: ROLE_INSTR }
        - { path: ^/portset/, role: ROLE_INSTR }
        - { path: ^/portitem/, role: ROLE_INSTR }
        - { path: ^/tag/, role: ROLE_INSTR }
        - { path: ^/tagset/, role: ROLE_INSTR }
        - { path: ^/team/, role: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN     
        